 <div class="footer-links quick-links w-100">
	 <div class="h5 text-accent-color d-block mb-3"><cms:get 'locale.quick_access'/></div>
	 <ul>
		 <li class="border-bottom border-dark"><a href="<cms:link 'about.php'/>" title="<cms:call 'get_page_title' tname='about.php'/>" class="w-100 d-block"><cms:call 'get_page_title' tname='about.php'/></a></li>
		<li class="border-bottom border-dark"><a href="<cms:link 'services.php'/>" title="<cms:call 'get_page_title' tname='services.php'/>" class="w-100 d-block"><cms:call 'get_page_title' tname='services.php'/></a></li>
		<li class="border-bottom border-dark"><a href="<cms:link 'doctors.php'/>" title="<cms:call 'get_page_title' tname='doctors.php'/>" class="w-100 d-block"><cms:call 'get_page_title' tname='doctors.php'/></a></li>
		<li class="border-bottom border-dark"><a href="<cms:link 'before-after.php'/>" title="<cms:call 'get_page_title' tname='before-after.php'/>" class="w-100 d-block"><cms:call 'get_page_title' tname='before-after.php'/></a></li>
		<li class="border-bottom border-dark"><a href="<cms:link 'insurance.php'/>" title="<cms:call 'get_page_title' tname='insurance.php'/>" class="w-100 d-block"><cms:call 'get_page_title' tname='insurance.php'/></a></li>
		<li class="border-bottom border-dark"><a href="<cms:link 'news-events.php'/>" title="<cms:call 'get_page_title' tname='news-events.php'/>" class="w-100 d-block"><cms:call 'get_page_title' tname='news-events.php'/></a></li>
		<li class="border-bottom border-dark"><a href="<cms:link 'insights.php'/>" title="<cms:call 'get_page_title' tname='insights.php'/>" class="w-100 d-block"><cms:call 'get_page_title' tname='insights.php'/></a></li>
		<li class="border-bottom border-dark"><a href="<cms:link 'testimonials.php'/>" title="<cms:call 'get_page_title' tname='testimonials.php'/>"><cms:call 'get_page_title' tname='testimonials.php'/></a></li>
		<li class="border-bottom border-dark"><a href="<cms:link 'careers.php'/>" title="<cms:call 'get_page_title' tname='careers.php'/>" class="w-100 d-block"><cms:call 'get_page_title' tname='careers.php'/></a></li>
		<li class="border-bottom border-dark"><a href="<cms:link 'pharmacy.php'/>" title="<cms:call 'get_page_title' tname='pharmacy.php'/>"><cms:call 'get_page_title' tname='pharmacy.php'/></a></li>
		<li class="border-bottom border-dark"><a href="<cms:link 'contact.php'/>" title="<cms:call 'get_page_title' tname='contact.php'/>" class="w-100 d-block"><cms:call 'get_page_title' tname='contact.php'/></a></li>
		
	</ul>
</div>