</div>
		</div>
		<!--end page wrapper -->
		
		
		<!--Start Back To Top Button--> <a href="javaScript:;" class="back-to-top"><i class='bx bxs-up-arrow-alt'></i></a>
		<!--End Back To Top Button-->
		<footer class="page-footer">
			<p class="small text-center m-0">Copyright &copy; <cms:date format='Y'/> Elyzee Hospital. All right reserved.</p>
		</footer>
	</div>
	<!--end wrapper-->
	

	<script src="<cms:show k_site_link/>hubspace/assets/js/bootstrap.bundle.min.js"></script>
	<script src="<cms:show k_site_link/>hubspace/assets/js/jquery.min.js"></script>
	<script src="<cms:show k_site_link/>hubspace/assets/plugins/metismenu/js/metisMenu.min.js"></script>
	<script src="<cms:show k_site_link/>hubspace/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js" "></script>
	<script src="<cms:show k_site_link/>hubspace/assets/plugins/datatable/js/jquery.dataTables.min.js"></script>
	<script src="<cms:show k_site_link/>hubspace/assets/plugins/datatable/js/dataTables.bootstrap5.min.js"></script>
	<script src="<cms:show k_site_link/>hubspace/assets/plugins/multiselect/select2.min.js"></script>
	
	<!--app JS-->
	<script src="<cms:show k_site_link/>hubspace/assets/js/app.js"></script>
</body>
</html>