<cms:trim "<cms:embed 'home/top_slider.inc'/>"/>
<cms:trim "<cms:embed 'contact/cta_sm_view.inc'/>"/>
<cms:trim "<cms:embed 'about/block_view.inc'/>"/>
<cms:trim "<cms:embed 'services/department_block_view.inc'/>"/>
<cms:trim "<cms:embed 'doctors/block_view.inc'/>"/>
<cms:trim "<cms:embed 'about/why_block_view.inc'/>"/>
<cms:trim "<cms:embed 'testimonials/block_view.inc' />"/>
<cms:trim "<cms:embed 'transformations/block_view.inc' />"/>
<cms:trim "<cms:embed 'about/how_block_view.inc'/>"/>

<cms:set block_template_name='insights.php'/>
<cms:set block_tile_name='insights/tile_view.inc'/>
<cms:trim "<cms:embed 'clonedpages/block_view.inc'/>"/>





  
