<section id="book_appointment" class="contact-us-form bg-black">
<div class="container">
<div class="row no-gutters">
<div class="col-lg-8">
<h6 class="d-none zero-size"><cms:get "locale.book_appointment"/></h6>
<div class="contact-form bg-dark">                         
<cms:trim "<cms:embed 'appointments/form_view.inc' />"/>
</div>
</div>

<div class="col-lg-4">
<cms:trim "<cms:embed 'contact/cta_gmap.inc' />"/>
</div>
</div>
</div>
</section>
